<?php

namespace Database\Seeders;

use App\Models\Kategori;
use App\Models\Kecamatan;
use App\Models\Tempat;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TempatSeeder extends Seeder
{
    public function run(): void
    {
        $kecamatan = Kecamatan::pluck('id', 'nama');
        $kategori = Kategori::pluck('id', 'nama');

        $data = [
            // RESTORAN
            [
                'nama_usaha' => 'Warung Tape Bu Tinuk',
                'kategori' => 'Restoran & Rumah Makan',
                'kecamatan' => 'Bondowoso Kota',
                'alamat' => 'Jl. Ahmad Yani No. 12, Bondowoso',
                'latitude' => -7.9078, 'longitude' => 113.8213,
                'no_telepon' => '081234567001',
                'harga_min' => 5000,  'harga_max' => 25000,
                'deskripsi' => 'Warung tape legendaris Bondowoso dengan cita rasa autentik. Menyajikan tape ubi dan tape singkong berkualitas tinggi sejak 1985.',
                'fasilitas' => ['parkir', 'take_away'],
                'jam_buka' => ['senin' => '07:00-21:00', 'selasa' => '07:00-21:00', 'minggu' => '07:00-17:00'],
                'kode_dispar' => 'REST-001', 'tgl_daftar_dispar' => '2022-01-15',
            ],
            [
                'nama_usaha' => 'RM Padang Sari Rasa',
                'kategori' => 'Restoran & Rumah Makan',
                'kecamatan' => 'Bondowoso Kota',
                'alamat' => 'Jl. Diponegoro No. 45, Bondowoso',
                'latitude' => -7.9102, 'longitude' => 113.8241,
                'no_telepon' => '081234567002',
                'harga_min' => 15000, 'harga_max' => 60000,
                'deskripsi' => 'Rumah makan Padang dengan masakan lezat dan porsi melimpah. Cocok untuk makan siang keluarga.',
                'fasilitas' => ['parkir', 'wifi', 'ac', 'toilet'],
                'jam_buka' => ['senin' => '08:00-22:00'],
                'kode_dispar' => 'REST-002', 'tgl_daftar_dispar' => '2022-03-10',
            ],
            [
                'nama_usaha' => 'Lesehan Kopi Arabika Ijen',
                'kategori' => 'Kafe & Kedai Kopi',
                'kecamatan' => 'Bondowoso Kota',
                'alamat' => 'Jl. Veteran No. 88, Bondowoso',
                'latitude' => -7.9065, 'longitude' => 113.8198,
                'no_telepon' => '081234567003',
                'harga_min' => 10000, 'harga_max' => 45000,
                'deskripsi' => 'Kedai kopi arabika asli Ijen. Menyajikan berbagai varian kopi specialty dari petani lokal Bondowoso.',
                'fasilitas' => ['wifi', 'ac', 'coworking', 'toilet', 'parking'],
                'jam_buka' => ['senin' => '09:00-23:00'],
                'kode_dispar' => 'REST-003', 'tgl_daftar_dispar' => '2022-06-20',
            ],
            [
                'nama_usaha' => 'Bakso President Bondowoso',
                'kategori' => 'Restoran & Rumah Makan',
                'kecamatan' => 'Grujugan',
                'alamat' => 'Jl. Raya Grujugan No. 23',
                'latitude' => -7.9356, 'longitude' => 113.8170,
                'no_telepon' => '081234567004',
                'harga_min' => 12000, 'harga_max' => 30000,
                'deskripsi' => 'Bakso berukuran besar dengan kuah kaldu sapi asli. Sudah terkenal di seluruh Bondowoso.',
                'fasilitas' => ['parkir', 'toilet'],
                'jam_buka' => ['senin' => '10:00-20:00'],
                'kode_dispar' => 'REST-004', 'tgl_daftar_dispar' => '2022-08-05',
            ],
            [
                'nama_usaha' => 'Sate Madura H. Cholil',
                'kategori' => 'Restoran & Rumah Makan',
                'kecamatan' => 'Curahdami',
                'alamat' => 'Jl. Curahdami Raya No. 15',
                'latitude' => -7.8778, 'longitude' => 113.8025,
                'no_telepon' => '081234567005',
                'harga_min' => 20000, 'harga_max' => 50000,
                'deskripsi' => 'Sate ayam dan kambing khas Madura dengan bumbu kacang spesial. Dimasak dengan arang batok kelapa.',
                'fasilitas' => ['parkir'],
                'jam_buka' => ['senin' => '11:00-22:00'],
                'kode_dispar' => 'REST-005', 'tgl_daftar_dispar' => '2022-09-12',
            ],
            [
                'nama_usaha' => 'Mie Jawa Bu Darmi',
                'kategori' => 'Restoran & Rumah Makan',
                'kecamatan' => 'Wonosari',
                'alamat' => 'Jl. Wonosari Selatan No. 7',
                'latitude' => -7.9523, 'longitude' => 113.8401,
                'no_telepon' => '081234567006',
                'harga_min' => 8000,  'harga_max' => 20000,
                'deskripsi' => 'Mie jawa kuah dengan telur dan ayam kampung. Cita rasa tradisional yang bikin nagih.',
                'fasilitas' => ['take_away'],
                'jam_buka' => ['senin' => '08:00-14:00'],
                'kode_dispar' => 'REST-006', 'tgl_daftar_dispar' => '2022-10-01',
            ],
            [
                'nama_usaha' => 'Kafe Bukit Ijen View',
                'kategori' => 'Kafe & Kedai Kopi',
                'kecamatan' => 'Sumber Wringin',
                'alamat' => 'Jl. Menuju Ijen KM 5, Sumber Wringin',
                'latitude' => -7.9901, 'longitude' => 113.9689,
                'no_telepon' => '081234567007',
                'harga_min' => 15000, 'harga_max' => 60000,
                'deskripsi' => 'Kafe dengan pemandangan perkebunan kopi dan Gunung Ijen. Spot foto terbaik di Bondowoso.',
                'fasilitas' => ['wifi', 'spot_foto', 'parkir', 'toilet'],
                'jam_buka' => ['senin' => '07:00-21:00'],
                'kode_dispar' => 'REST-007', 'tgl_daftar_dispar' => '2023-01-10',
            ],
            [
                'nama_usaha' => 'Toko Oleh-Oleh Tape Bondowoso',
                'kategori' => 'Bakeri & Jajanan',
                'kecamatan' => 'Bondowoso Kota',
                'alamat' => 'Jl. PB Sudirman No. 34, Bondowoso',
                'latitude' => -7.9088, 'longitude' => 113.8235,
                'no_telepon' => '081234567008',
                'harga_min' => 10000, 'harga_max' => 100000,
                'deskripsi' => 'Pusat oleh-oleh tape khas Bondowoso. Tersedia berbagai varian tape, dodol, dan snack lokal.',
                'fasilitas' => ['parkir', 'ac'],
                'jam_buka' => ['senin' => '08:00-20:00'],
                'kode_dispar' => 'REST-008', 'tgl_daftar_dispar' => '2023-02-14',
            ],

            // HOTEL
            [
                'nama_usaha' => 'Hotel Rembangan Bondowoso',
                'kategori' => 'Hotel & Resort',
                'kecamatan' => 'Bondowoso Kota',
                'alamat' => 'Jl. Rembangan No. 1, Bondowoso',
                'latitude' => -7.9045, 'longitude' => 113.8178,
                'no_telepon' => '0332-421234',
                'harga_min' => 250000, 'harga_max' => 750000,
                'deskripsi' => 'Hotel bintang 3 terbaik di Bondowoso. Fasilitas lengkap dengan kolam renang dan restoran.',
                'fasilitas' => ['kolam_renang', 'restoran', 'wifi', 'ac', 'parkir', 'laundry', '24jam'],
                'jam_buka' => ['checkin' => '14:00', 'checkout' => '12:00'],
                'kode_dispar' => 'HTL-001', 'tgl_daftar_dispar' => '2021-06-01',
            ],
            [
                'nama_usaha' => 'Hotel d\'Season Bondowoso',
                'kategori' => 'Hotel & Resort',
                'kecamatan' => 'Bondowoso Kota',
                'alamat' => 'Jl. Diponegoro No. 79, Bondowoso',
                'latitude' => -7.9115, 'longitude' => 113.8258,
                'no_telepon' => '0332-425678',
                'harga_min' => 180000, 'harga_max' => 450000,
                'deskripsi' => 'Hotel modern di pusat kota Bondowoso. Dekat dengan pusat perbelanjaan dan kuliner.',
                'fasilitas' => ['wifi', 'ac', 'parkir', 'restoran', 'meeting_room'],
                'jam_buka' => ['checkin' => '14:00', 'checkout' => '12:00'],
                'kode_dispar' => 'HTL-002', 'tgl_daftar_dispar' => '2021-08-15',
            ],
            [
                'nama_usaha' => 'Homestay Ijen Hijau',
                'kategori' => 'Penginapan & Homestay',
                'kecamatan' => 'Sumber Wringin',
                'alamat' => 'Desa Sumber Wringin, Kec. Sumber Wringin',
                'latitude' => -7.9895, 'longitude' => 113.9671,
                'no_telepon' => '081234567009',
                'harga_min' => 150000, 'harga_max' => 300000,
                'deskripsi' => 'Homestay nyaman dekat akses pendakian Kawah Ijen. Sarapan pagi termasuk.',
                'fasilitas' => ['sarapan', 'wifi', 'parkir', 'guiding_service'],
                'jam_buka' => ['checkin' => '13:00', 'checkout' => '11:00'],
                'kode_dispar' => 'HTL-003', 'tgl_daftar_dispar' => '2022-02-20',
            ],
            [
                'nama_usaha' => 'Villa Kopi Arabika',
                'kategori' => 'Villa & Cottages',
                'kecamatan' => 'Sumber Wringin',
                'alamat' => 'Jl. Perkebunan Ijen, Sumber Wringin',
                'latitude' => -7.9912, 'longitude' => 113.9645,
                'no_telepon' => '081234567010',
                'harga_min' => 500000, 'harga_max' => 1200000,
                'deskripsi' => 'Villa eksklusif di tengah kebun kopi arabika Ijen. Pemandangan sunrise spektakuler.',
                'fasilitas' => ['private_pool', 'bbq', 'wifi', 'parkir', 'dapur'],
                'jam_buka' => ['checkin' => '15:00', 'checkout' => '11:00'],
                'kode_dispar' => 'HTL-004', 'tgl_daftar_dispar' => '2022-05-10',
            ],
            [
                'nama_usaha' => 'Hotel Grand Situbondo',
                'kategori' => 'Hotel & Resort',
                'kecamatan' => 'Tenggarang',
                'alamat' => 'Jl. Raya Tenggarang No. 45',
                'latitude' => -7.8645, 'longitude' => 113.8578,
                'no_telepon' => '081234567011',
                'harga_min' => 200000, 'harga_max' => 500000,
                'deskripsi' => 'Hotel strategis di jalur utama Bondowoso-Situbondo. Cocok untuk transit bisnis.',
                'fasilitas' => ['wifi', 'ac', 'parkir', 'restoran'],
                'jam_buka' => ['checkin' => '14:00', 'checkout' => '12:00'],
                'kode_dispar' => 'HTL-005', 'tgl_daftar_dispar' => '2022-07-01',
            ],

            // EKRAF
            [
                'nama_usaha' => 'Batik Bondowoso Srikandi',
                'kategori' => 'Batik & Tenun',
                'kecamatan' => 'Bondowoso Kota',
                'alamat' => 'Jl. Batik No. 12, Bondowoso',
                'latitude' => -7.9098, 'longitude' => 113.8221,
                'no_telepon' => '081234567012',
                'harga_min' => 75000,  'harga_max' => 500000,
                'deskripsi' => 'Produsen dan galeri batik khas Bondowoso. Motif bunga kopi dan pemandangan Ijen.',
                'fasilitas' => ['parkir', 'workshop', 'galeri'],
                'jam_buka' => ['senin' => '08:00-17:00', 'minggu' => 'tutup'],
                'kode_dispar' => 'EKR-001', 'tgl_daftar_dispar' => '2022-04-05',
            ],
            [
                'nama_usaha' => 'Pengrajin Keramik Maesan',
                'kategori' => 'Kerajinan Tangan',
                'kecamatan' => 'Maesan',
                'alamat' => 'Desa Maesan Barat, Kec. Maesan',
                'latitude' => -8.0134, 'longitude' => 113.7823,
                'no_telepon' => '081234567013',
                'harga_min' => 15000,  'harga_max' => 250000,
                'deskripsi' => 'Sentra pengrajin keramik tradisional Maesan. Berbagai produk keramik untuk dekorasi.',
                'fasilitas' => ['workshop', 'galeri'],
                'jam_buka' => ['senin' => '08:00-16:00'],
                'kode_dispar' => 'EKR-002', 'tgl_daftar_dispar' => '2022-05-20',
            ],
            [
                'nama_usaha' => 'Kopi Arabika Ijen Premium',
                'kategori' => 'Kuliner Oleh-Oleh',
                'kecamatan' => 'Sumber Wringin',
                'alamat' => 'Jl. Perkebunan No. 3, Sumber Wringin',
                'latitude' => -7.9878, 'longitude' => 113.9656,
                'no_telepon' => '081234567014',
                'harga_min' => 50000,  'harga_max' => 300000,
                'deskripsi' => 'Produsen kopi arabika Ijen specialty langsung dari petani. Proses natural, honey, dan washed.',
                'fasilitas' => ['tasting', 'packaging', 'parkir'],
                'jam_buka' => ['senin' => '08:00-17:00'],
                'kode_dispar' => 'EKR-003', 'tgl_daftar_dispar' => '2022-06-01',
            ],
            [
                'nama_usaha' => 'Sanggar Seni Budaya Bondowoso',
                'kategori' => 'Seni & Pertunjukan',
                'kecamatan' => 'Bondowoso Kota',
                'alamat' => 'Jl. Kesenian No. 5, Bondowoso',
                'latitude' => -7.9071, 'longitude' => 113.8207,
                'no_telepon' => '081234567015',
                'harga_min' => 25000,  'harga_max' => 150000,
                'deskripsi' => 'Sanggar seni tari, musik tradisional, dan pertunjukan budaya Bondowoso.',
                'fasilitas' => ['stage', 'parkir', 'toilet'],
                'jam_buka' => ['selasa' => '16:00-21:00', 'sabtu' => '09:00-21:00'],
                'kode_dispar' => 'EKR-004', 'tgl_daftar_dispar' => '2022-07-10',
            ],
            [
                'nama_usaha' => 'Galeri Anyaman Bambu Wringin',
                'kategori' => 'Kerajinan Tangan',
                'kecamatan' => 'Wringin',
                'alamat' => 'Desa Wringin Agung, Kec. Wringin',
                'latitude' => -7.9689, 'longitude' => 113.9356,
                'no_telepon' => '081234567016',
                'harga_min' => 20000,  'harga_max' => 400000,
                'deskripsi' => 'Pusat kerajinan anyaman bambu kualitas ekspor. Furniture, dekorasi, dan souvenir.',
                'fasilitas' => ['galeri', 'workshop', 'parkir'],
                'jam_buka' => ['senin' => '08:00-17:00'],
                'kode_dispar' => 'EKR-005', 'tgl_daftar_dispar' => '2022-08-22',
            ],
            [
                'nama_usaha' => 'Tape Uli Khas Bondowoso Bu Sari',
                'kategori' => 'Kuliner Oleh-Oleh',
                'kecamatan' => 'Bondowoso Kota',
                'alamat' => 'Jl. Kembar No. 19, Bondowoso',
                'latitude' => -7.9110, 'longitude' => 113.8250,
                'no_telepon' => '081234567017',
                'harga_min' => 15000,  'harga_max' => 80000,
                'deskripsi' => 'Tape uli oleh-oleh khas paling terkenal di Bondowoso. Dibuat dari singkong pilihan.',
                'fasilitas' => ['take_away', 'pengiriman'],
                'jam_buka' => ['senin' => '06:00-18:00'],
                'kode_dispar' => 'EKR-006', 'tgl_daftar_dispar' => '2022-09-05',
            ],
            [
                'nama_usaha' => 'Batik Tulis Prajekan',
                'kategori' => 'Batik & Tenun',
                'kecamatan' => 'Prajekan',
                'alamat' => 'Jl. Prajekan Lor No. 8, Prajekan',
                'latitude' => -7.8023, 'longitude' => 113.9034,
                'no_telepon' => '081234567018',
                'harga_min' => 100000, 'harga_max' => 800000,
                'deskripsi' => 'Batik tulis asli Prajekan dengan motif khas budaya Madura-Jawa. Pewarna alam.',
                'fasilitas' => ['galeri', 'workshop', 'parkir'],
                'jam_buka' => ['senin' => '08:00-16:00', 'minggu' => 'tutup'],
                'kode_dispar' => 'EKR-007', 'tgl_daftar_dispar' => '2022-10-15',
            ],
            [
                'nama_usaha' => 'Penginapan Alam Klabang',
                'kategori' => 'Penginapan & Homestay',
                'kecamatan' => 'Klabang',
                'alamat' => 'Jl. Klabang Baru No. 6',
                'latitude' => -7.9023, 'longitude' => 113.9134,
                'no_telepon' => '081234567019',
                'harga_min' => 100000, 'harga_max' => 250000,
                'deskripsi' => 'Penginapan bernuansa alam dengan harga terjangkau di kawasan Klabang.',
                'fasilitas' => ['parkir', 'wifi', 'breakfast'],
                'jam_buka' => ['checkin' => '13:00', 'checkout' => '11:00'],
                'kode_dispar' => 'HTL-006', 'tgl_daftar_dispar' => '2023-01-20',
            ],
            [
                'nama_usaha' => 'Warung Pecel Bu Ningsih',
                'kategori' => 'Restoran & Rumah Makan',
                'kecamatan' => 'Tapen',
                'alamat' => 'Jl. Tapen Raya No. 14',
                'latitude' => -7.8432, 'longitude' => 113.8902,
                'no_telepon' => '081234567020',
                'harga_min' => 8000,  'harga_max' => 20000,
                'deskripsi' => 'Pecel lele dan ayam goreng warung pinggir jalan yang selalu ramai. Harga merakyat.',
                'fasilitas' => ['take_away'],
                'jam_buka' => ['senin' => '10:00-22:00'],
                'kode_dispar' => 'REST-009', 'tgl_daftar_dispar' => '2023-02-01',
            ],
            [
                'nama_usaha' => 'Oleh-Oleh Kopi Robusta Lereng Raung',
                'kategori' => 'Kuliner Oleh-Oleh',
                'kecamatan' => 'Maesan',
                'alamat' => 'Jl. Lereng Raung No. 2, Maesan',
                'latitude' => -8.0115, 'longitude' => 113.7798,
                'no_telepon' => '081234567021',
                'harga_min' => 30000,  'harga_max' => 200000,
                'deskripsi' => 'Kopi robusta pilihan dari lereng Gunung Raung. Tersedia dalam berbagai kemasan.',
                'fasilitas' => ['tasting', 'parkir'],
                'jam_buka' => ['senin' => '07:00-18:00'],
                'kode_dispar' => 'EKR-008', 'tgl_daftar_dispar' => '2023-03-10',
            ],
        ];

        foreach ($data as $d) {
            $kat = Kategori::where('nama', $d['kategori'])->first();
            $kec = Kecamatan::where('nama', $d['kecamatan'])->first();
            if (! $kat || ! $kec) {
                continue;
            }

            Tempat::create([
                'id' => (string) Str::uuid(),
                'kategori_id' => $kat->id,
                'kecamatan_id' => $kec->id,
                'nama_usaha' => $d['nama_usaha'],
                'alamat' => $d['alamat'],
                'latitude' => $d['latitude'],
                'longitude' => $d['longitude'],
                'no_telepon' => $d['no_telepon'],
                'jam_buka' => $d['jam_buka'],
                'harga_min' => $d['harga_min'],
                'harga_max' => $d['harga_max'],
                'deskripsi' => $d['deskripsi'],
                'fasilitas' => $d['fasilitas'],
                'status' => 'aktif',
                'sumber_dispar' => true,
                'kode_dispar' => $d['kode_dispar'],
                'tgl_daftar_dispar' => $d['tgl_daftar_dispar'],
            ]);
        }
    }
}
